project_id = "riqjidlyjyhfpgnjtbqi"

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

[functions.razorpay-settings]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = false

[functions.email-triggers]
verify_jwt = false